document.addEventListener('DOMContentLoaded', function() {
    // We need to wait for the map to be fully initialized and for window variables to be available.
    // QGIS2Web typically initializes the map at the end of layers.js or in qgis2web.js.
    // We'll give it a short timeout or just attach to the button.
    
    const analyzeBtn = document.getElementById('btn-analyze');
    const resultsPanel = document.getElementById('analysis-results');
    
    if (analyzeBtn) {
        analyzeBtn.addEventListener('click', performAnalysis);
    }
    
    const groupSelect = document.getElementById('group-select');
    if (groupSelect) {
        groupSelect.addEventListener('change', function() {
            zoomToGroup(this.value);
        });
        setTimeout(() => {
            if (typeof map !== 'undefined') zoomToGroup(groupSelect.value);
        }, 500);
    }
    
    if (resultsPanel) {
        resultsPanel.addEventListener('click', function(e) {
            const item = e.target.closest('.result-item');
            if (item && typeof map !== 'undefined') {
                const extStr = item.getAttribute('data-extent');
                if (extStr) {
                    const ext = extStr.split(',').map(Number);
                    map.getView().fit(ext, { duration: 800, maxZoom: 16, padding: [100, 100, 100, 100] });
                }
            }
        });
    }
    
    function zoomToGroup(groupId) {
        if (typeof map === 'undefined' || typeof ol === 'undefined') return;
        
        let groupsToProcess = [];
        if (groupId === 'all') {
            groupsToProcess = [
                window['group_Grupo1TiquelTiuquilemu'],
                window['group_Grupo5LongoviloNavidad'],
                window['group_Grupo7RioViejoGuanguali']
            ].filter(Boolean);
        } else {
            const group = window[groupId];
            if (group) groupsToProcess.push(group);
        }
        
        if (groupsToProcess.length === 0) return;
        
        let combinedExtent = ol.extent.createEmpty();
        groupsToProcess.forEach(g => {
            g.getLayers().getArray().forEach(layer => {
                const source = layer.getSource();
                if (source && typeof source.getExtent === 'function') {
                    const ext = source.getExtent();
                    if (ext) ol.extent.extend(combinedExtent, ext);
                }
            });
        });
        
        if (!ol.extent.isEmpty(combinedExtent) && combinedExtent[0] !== Infinity) {
            map.getView().fit(combinedExtent, { duration: 1000, padding: [50, 50, 50, 50] });
        }
    }
    
    function performAnalysis() {
        if (typeof jsts === 'undefined') {
            resultsPanel.innerHTML = '<span style="color:red;">Error: JSTS library not loaded.</span>';
            return;
        }
        
        analyzeBtn.disabled = true;
        analyzeBtn.innerText = 'Analizando...';
        resultsPanel.innerHTML = '<em>Calculando distancias e intersecciones...</em>';
        
        // Use setTimeout to allow UI to update before heavy synchronous calculations
        setTimeout(() => {
            try {
                runAnalysisLogic();
            } catch (e) {
                console.error(e);
                resultsPanel.innerHTML = '<span style="color:red;">Error durante el análisis: ' + e.message + '</span>';
            } finally {
                analyzeBtn.disabled = false;
                analyzeBtn.innerText = 'Analizar Intersecciones y Cercanías';
            }
        }, 100);
    }
    
    function runAnalysisLogic() {
        // Get user inputs
        const selectedGroupId = document.getElementById('group-select').value;
        const bufferDistance = parseFloat(document.getElementById('distance-buffer').value) || 5000; // in meters
        
        // Access global variables generated by QGIS2Web
        const targetGroups = [
            window['group_Planificacin'],
            window['group_MedioNatural'],
            window['group_MedioCultural'],
            window['group_CONADI']
        ];
        
        let sourceLayers = [];
        if (selectedGroupId === 'all') {
            const allGroups = [
                window['group_Grupo1TiquelTiuquilemu'],
                window['group_Grupo5LongoviloNavidad'],
                window['group_Grupo7RioViejoGuanguali']
            ];
            allGroups.forEach(g => {
                if (g) sourceLayers.push(...g.getLayers().getArray());
            });
            if (sourceLayers.length === 0) throw new Error('No se encontraron capas de proyectos.');
        } else {
            const selectedGroup = window[selectedGroupId];
            if (!selectedGroup) throw new Error('Grupo seleccionado no encontrado.');
            sourceLayers = selectedGroup.getLayers().getArray();
        }
        
        // Initialize JSTS parser for OpenLayers
        const parser = new jsts.io.OL3Parser();
        // Inject standard OpenLayers geometry types safely
        parser.inject(
            ol.geom.Point || function(){},
            ol.geom.LineString || function(){},
            ol.geom.LinearRing || function(){},
            ol.geom.Polygon || function(){},
            ol.geom.MultiPoint || function(){},
            ol.geom.MultiLineString || function(){},
            ol.geom.MultiPolygon || function(){},
            ol.geom.GeometryCollection || function(){}
        );
        
        // Helper to flatten GeometryCollections to avoid JSTS distance error
        function extractGeoms(jstsGeom, targetArray) {
            if (!jstsGeom) return;
            if (jstsGeom.getGeometryType() === 'GeometryCollection') {
                for (let i = 0; i < jstsGeom.getNumGeometries(); i++) {
                    extractGeoms(jstsGeom.getGeometryN(i), targetArray);
                }
            } else {
                targetArray.push(jstsGeom);
            }
        }
        
        // 1. Collect all JSTS geometries of the selected group
        const sourceGeoms = [];
        
        sourceLayers.forEach(layer => {
            const source = layer.getSource();
            if (source && typeof source.getFeatures === 'function') {
                const features = source.getFeatures();
                features.forEach(feature => {
                    const geom = feature.getGeometry();
                    if (geom) {
                        try {
                            if (geom.getType() === 'GeometryCollection') {
                                geom.getGeometries().forEach(g => {
                                    extractGeoms(parser.read(g), sourceGeoms);
                                });
                            } else {
                                extractGeoms(parser.read(geom), sourceGeoms);
                            }
                        } catch(e) {
                            console.warn("Could not parse source geom", e);
                        }
                    }
                });
            }
        });
        
        if (sourceGeoms.length === 0) {
            resultsPanel.innerHTML = '<em>El grupo seleccionado no tiene geometrías válidas.</em>';
            return;
        }
        
        // 2. Analyze against target layers
        const resultsByLayer = {};
        
        targetGroups.forEach(group => {
            if (!group) return;
            const layers = group.getLayers().getArray();
            
            layers.forEach(layer => {
                const layerTitle = layer.get('title') || 'Capa sin nombre';
                // Clean up title (remove HTML like img tags)
                const cleanTitle = layerTitle.replace(/<[^>]*>?/gm, '').trim();
                
                const source = layer.getSource();
                if (source && typeof source.getFeatures === 'function') {
                    const features = source.getFeatures();
                    
                    features.forEach(feature => {
                        const geom = feature.getGeometry();
                        if (geom) {
                            const targetGeoms = [];
                            try {
                                if (geom.getType() === 'GeometryCollection') {
                                    geom.getGeometries().forEach(g => {
                                        extractGeoms(parser.read(g), targetGeoms);
                                    });
                                } else {
                                    extractGeoms(parser.read(geom), targetGeoms);
                                }
                            } catch(e) {
                                console.warn("Error parsing target geom", e);
                            }
                            
                            if (targetGeoms.length === 0) return;
                            
                            // Calculate exact minimum distance between any source part and any target part
                            let minDistance = Infinity;
                            
                            for (const srcGeom of sourceGeoms) {
                                for (const tgtGeom of targetGeoms) {
                                    try {
                                        const d = srcGeom.distance(tgtGeom);
                                        if (d < minDistance) {
                                            minDistance = d;
                                        }
                                    } catch (err) {
                                        console.warn("Distance calc error", err);
                                    }
                                }
                            }
                            
                            const distance = minDistance;
                            
                            if (distance <= bufferDistance) {
                                if (!resultsByLayer[cleanTitle]) {
                                    resultsByLayer[cleanTitle] = [];
                                }
                                
                                // Try to get a meaningful name from the feature properties
                                const props = feature.getProperties();
                                let featureName = props['NOMBRE'] || props['nombre'] || props['Name'] || props['nom_comuna'] || props['comunidad'] || props['id'] || 'Elemento';
                                
                                // Lógica específica para Inventario de Humedales
                                if (props['COD_HUMEDA'] !== undefined || props['NOM_HUMDET'] !== undefined) {
                                    const cod = props['COD_HUMEDA'] || 'Sin código';
                                    const nom = props['NOM_HUMDET'] || 'Sin nombre';
                                    featureName = `${cod} - ${nom}`;
                                }
                                
                                const ext = feature.getGeometry().getExtent();
                                
                                // Se agrega cada elemento individual encontrado, sin sobrescribir
                                // aquellos que compartan el mismo nombre o carezcan de él.
                                resultsByLayer[cleanTitle].push({
                                    name: featureName,
                                    distance: distance,
                                    extent: ext
                                });
                            }
                        }
                    });
                }
            });
        });
        
        // 3. Render results
        renderResults(resultsByLayer, bufferDistance);
    }
    
    function renderResults(results, bufferDistance) {
        if (Object.keys(results).length === 0) {
            resultsPanel.innerHTML = '<em>No se encontraron atributos a menos de ' + bufferDistance + ' metros.</em>';
            return;
        }
        
        let html = '';
        
        for (const [layerName, items] of Object.entries(results)) {
            // Sort items by distance
            items.sort((a, b) => a.distance - b.distance);
            
            html += `<div class="result-group">
                        <div class="result-layer-title">${layerName} (${items.length})</div>`;
                        
            items.forEach(item => {
                const isIntersect = item.distance === 0;
                const itemClass = isIntersect ? 'intersect-item' : 'proximity-item';
                const distText = isIntersect ? 'Intersección' : `A ${Math.round(item.distance)} metros`;
                const extStr = item.extent ? item.extent.join(',') : '';
                
                html += `<div class="result-item ${itemClass}" data-extent="${extStr}" title="Clic para hacer zoom">
                            <span class="feature-name">${item.name}</span><br>
                            <span class="distance-label">${distText}</span>
                         </div>`;
            });
            
            html += `</div>`;
        }
        
        resultsPanel.innerHTML = html;
    }
});
